### ISSUE TITLE
Enable Sanitizer in Debug Build and Unit Tests

### ISSUE THREAD

**Issue by elfenpiff** [eclipse/iceoryx#141]
## Brief feature description
Add the following compiler flags for the Linux (and MacOS build, if possible)
```-fsanitize=address -fsanitze=undefined```. All unit tests have to run without undefined behavior, memory leaks or other funky memory effects.

## Detailed information

We can a avoid a wide variety of bugs when this is activated in the github CI.

**Comment by mossmaurice** [comment]
> 
> 
> Is this setting required only for CI build ?

Yeah, I would recommend to use the settings only for the CI.

@elfenpiff Opinions?

**Comment by SoftwareApe** [comment]
Don't forget you also need to scan the output for the different types of errors that asan and ubsan output. UBSan usually uses the normal gcc/clang warning format but saying "runtime error" instead of "warning" or "error.

ASan output looks a bit more like valgrind. You have the LeakSanitizer and AddressSanitizer failures to scan for.

**Comment by SoftwareApe** [comment]
I would also suggest activating some additional ubsan flags:
`-fsanitize=float-divide-by-zero`:
Detect division by zero on floats. I would expect this to never happen on a safety critical project.
