### ISSUE TITLE
remove blinking warning in Roudi

### ISSUE THREAD

**Issue by Karsten1987** [eclipse/iceoryx#85]
The warning of `Could not open file '/etc/iceoryx/roudi_config.toml'.` is somewhat misleading as it doesn't give the user any more info about what's happening.

Not only does it (annoyingly) blink, the RouDi application runs perfectly fine. 

If you look at the two warnings around that, I don't see why this warning has to be red and blinking:
```
2020-04-13 17:36:36.144 [ Info  ]: No config file provided. Using /etc/iceoryx/roudi_config.toml
Could not open file '/etc/iceoryx/roudi_config.toml'.
2020-04-13 17:36:36.144 [ Info  ]: No config file found at /etc/iceoryx/roudi_config.toml. Falling back to built-in config.
```

**Comment by evshary** [comment]
It seems like these info messages can't be hided by running RouDi command like this `RouDi -l off`.
The reason might be that RouDi tries to [get the config](https://github.com/eclipse/iceoryx/blob/master/iceoryx_posh/source/roudi/application/roudi_main.cpp#L29
) before setting log level.

BTW, I'm not sure why some message uses std:cerr instead of iceoryx log function. Is there any reason? (If it's off-topic, I can open another issue to discuss this.)

**Comment by budrus** [comment]
@evshary good point, I will open the issue. Different logger were used in the past. I guess a cleanup is needed. Sometimes a dependency to a logger in quite low layer modules in the utils was undesired. But there is no clear strategy now

**Comment by elBoberido** [comment]
yes, this should not blink and also not be printed. It should just print which config is used.

**Comment by budrus** [comment]
i created a separate issue for the logger topic #130
